### ISSUE TITLE
SwapMonitors Shortcut - Symbol not found

### ISSUE THREAD

**Issue by austinlyon** [alin23/mac-utils#1]
Read your article on "weird monitor bugs" and the monitor swapping problem really hit home with me. I've been searching for an elegant solution, and while some people have more than two external monitors, running a script from Shortcuts would be perfect for my dual monitor setup, thank you for this!

I'm getting a linking error when I run the script:
```
dyld[27402]: Symbol not found: (_$s10Foundation22_convertNSErrorToErrorys0E0_pSo0C0CSgF)
Referenced from: '/Users/myUserName/.bin/SwapMonitors'
Expected in: '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation'
```

I'm no Swift dev, so I apologize if this isn't helpful or is specific to my machine.

**Comment by alin23** [comment]
Thanks for letting me know!

It seems I didn't specify the minimum macOS version for compatiblity. I have recompiled the binaries for macOS 10.15.4 and later.

Try removing `~/.bin/SwapMonitors` and running the Shortcut again.
