### ISSUE TITLE
SwapMonitors swaps wrong displays

### ISSUE THREAD

**Issue by dr808** [alin23/mac-utils#3]
Using `SwapMonitors` on MBP 16" Intel with eGPU and two external displays results in the app swapping built-in display with one of the monitors but not the two external displays.

There are two issues here. First, nothing actually swaps between the built-in display and VG280K. The second, and the real issue for me, as that I'd like the external displays to swap only.

Output is as follows:

```
Swapping Built-in Retina Display [ID: 69734662] with VG280K [ID: 478245321]

External Display 1: x=-2048.0 y=0.0 width=2048.0 height=1280.0
	Moving to: x=3840.0 y=0.0

External Display 2: x=3840.0 y=0.0 width=3840.0 height=2160.0
	Moving to: x=-2048.0 y=0.0
```

I'm so grateful that you took the time and initiative to build something to address this annoying issue! Thanks!

**Comment by alin23** [comment]
Thank you for the report!

Run `SwapMonitors print-ids` to get the display ids and then you can specify the correct ids to swap manually. 

The auto detection is not supposed to be flawless, it's mostly a best guess.
