### ISSUE TITLE
Question: moving windows when swapping monitors

### ISSUE THREAD

**Issue by bennyweise** [alin23/mac-utils#4]
Hi, I'm very glad to come across this set of utils (great work on Lunar as well, btw). I have a question about the SwapMonitors functionality - I'm using it for the standard reason of MacOS not recognising my two identical monitors consistently. When waking from sleep, I often have everything swapped around, and would ideally restore to the original setup which would include the position of windows on each monitor. Do you know of a way this could be achieved?

**Comment by alin23** [comment]
Thanks for the kind words!

I'm not sure I understand the request. 

To explain: When monitors get swapped, the right monitor goes to the left and viceversa. 

But what you see on the monitors stays the same, only the coordinates change so that the mouse cursor goes to the correct monitor when it reaches a boundary. 

Are you saying that you also want the contents to be swapped? So all the windows from the left monitor should move to the right monitor and viceversa?

**Comment by bennyweise** [comment]
Thanks for the quick response! Hopefully I can explain a little better with a few diagrams. So, firstly a little more info about my setup - I have a MacBook with two portable USB-C displays attached to each side (Packed Pixels displays). Due to the mounting system they are set at rotations of 90˚ and 270˚. 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/4620206/208053856-192ce903-21f3-4ce7-9a8d-a38792047225.png">

Above image shows how I regularly work - e.g. Terminal as Window 1 on the left hand side. Now when the system comes out of sleep, sometimes the monitors are switched - in this case everything ends up upside down:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/4620206/208054090-a656d7cd-74a2-4d17-81bb-1288897f18b9.png">

So the SwapMonitor shortcut is great in that it quickly corrects for this, and puts them back in the correct location. The only problem is that the windows previously on the left side are now on the right monitor. Note Window 1 now on the RHS in the pic below:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/4620206/208054279-a1782475-b409-4ed9-8f21-99c5fa529e82.png">

So it would be perfect to have the option for the windows to keep their absolute position in the display layout, rather than staying with the same monitor they were on when the system came out of sleep.

Does that make sense?

**Comment by alin23** [comment]
Yes it makes sense, but it's not a matter of "keeping the windows position". SwapMonitors doesn't handle windows in any way, it simply swaps the screen coordinates. macOS is the one swapping windows.

A lot more code would be needed to use the Accessibility API, get a list of windows and their positions for each monitor, move the windows around between the two monitors, and handle edge cases about monitors that may have different resolutions.

Unfortunately that's out of scope for SwapMonitors. You may have better luck using something like [yabai](https://github.com/koekeishiya/yabai) to move the windows between each monitor. It has a handy command line that can:

- get a window list for a display

```sh
yabai -m query --windows --display 2  # or any display number
```

- move a window to a specific display

```sh
yabai -m window --display 2  # or any display number
```
