### ISSUE TITLE
Unable to compile darwin arm64

### ISSUE THREAD

**Issue by neo773** [alin23/mac-utils#6]
I'm unable to compile this on my M1 MBP

```
neo@neos-MacBook-Pro-2 mac-utils % make all
error: link command failed with exit code 1 (use -v to see invocation)
ld: open() failed, errno=2 for 'bin/HorizontalMonitorLayout-arm64'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: fatalError
make: *** [bin/HorizontalMonitorLayout] Error 1
neo@neos-MacBook-Pro-2 mac-utils % 
```

**Comment by alin23** [comment]
Try adding -v to the clang command in the Makefile to see where it fails for you. It works on my end so I can't help without more details.

**Comment by neo773** [comment]
Closing this as I ended up using https://github.com/oschrenk/keyboard.swift/ I only needed the keyboard brightness controller
