### ISSUE TITLE
ToggleHDR shows built-in monitor as not supporting HDR on Ventura.

### ISSUE THREAD

**Issue by j3pic** [alin23/mac-utils#7]
I know the monitor does support HDR because I can see the monitor cranking up the brightness whenever an HDR video has any pixels on screen. 

```
$ toggle-hdr
ID      UUID                                    Supports HDR    HDR Enabled     Name
1       37D8832A-2D66-02CA-B9F7-8F30A301B230    false           false           Built-in Retina Display
```

Try to turn HDR off anyway and it says:

```
The display does not support HDR control: Built-in Retina Display [ID: 1]
```

I downloaded this app because I found that Ventura has no option to turn off HDR in its display settings. I seem to just be stuck with super-bright HDR videos no matter what.

**Comment by alin23** [comment]
The built in monitor has its own automatic HDR, it cannot be controlled by the API used in ToggleHDR. That API is only helpful for external monitors.
