### ISSUE TITLE
Switch to 60 Hz when HDR isn't detected?

### ISSUE THREAD

**Issue by tcobbs** [alin23/mac-utils#9]
I have a 4K HDR display that supports up to 144 Hz (in both SDR and HDR). I have it set to "look like" 1440p (with HiDPI), so it behaves like a 5K display. Unfortunately, recent versions of macOS don't support HDR in "looks like 5K" mode even though the display itself supports it. I was able to create a tweaked version of ToggleHDR that does the following:

If HDR is not supported by the display, then:

1. Record the original mode (and write the mode number and `display.name` to `UserDefaults`). 
2. Look for a 60 Hz version of the same mode.
3. If it finds it, switch to that mode.
4. If the display then supports HDR, toggle HDR on.
5. If the display _still_ doesn't support HDR, restore the original mode and print an error.

The reason for storing the data to `UserDefaults` in step 1 is that if "toggle" is requested and it's already in HDR mode, and the `display.name` matches the one stored in UserDefaults, and the mode number successfully creates a mode, it will then restore that mode (so that switching HDR off doesn't leave you stuck in 60 Hz).

Even though I got all this working, my code isn't very clean, so I'm wondering if you are interested in implementing something similar, but doing it right. Or, alternatively, if you are interested in me cleaning it up and submitting a PR. (I probably won't bother to clean it up if you're not interested in accepting a PR.) My code does one other thing, which is if the command line doesn't contain any arguments at all (other than the executable), and the system only contains 1 display, it will assume that the user wants to toggle HDR on the sole display.

**Comment by alin23** [comment]
Hi @tcobbs ! Thanks for the info!

Sure, I'd love to take a look and see if I can add it to the repo.

**Comment by tcobbs** [comment]
Great! PR is created:

https://github.com/alin23/mac-utils/pull/10
